# Generated by Django 4.0.4 on 2022-05-26 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=512)),
                ('type', models.CharField(choices=[('FUN', 'fundacja'), ('ORG', 'organizacja pozarządowa'), ('ZBI', 'zbiórka lokalna')], default='FUN', max_length=128)),
                ('categories', models.ManyToManyField(to='rakieta.category')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('address', models.CharField(max_length=128)),
                ('phone_number', models.IntegerField()),
                ('city', models.CharField(max_length=64)),
                ('zip_code', models.CharField(max_length=24)),
                ('pick_up_date', models.DateField()),
                ('pick_up_time', models.DateTimeField()),
                ('pick_up_comment', models.TextField(max_length=258)),
                ('categories', models.ManyToManyField(to='rakieta.category')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rakieta.institution')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
